### ISSUE TITLE
Preserving quantitative pixel level spectral information

### ISSUE THREAD

**Issue by martingosnell** [mabdelhack/hyperspectral_image_generator#9]

**Comment by mabdelhack** [comment]
Hi Martin,

There is a function to calculate the mean and std of the training set.

In general, it is better for ML models to have the data normalized so you can depend on the spatial patterns in each spectral layer without one dominating the others. If quantitative information is needed, then it would be better to include it in the model concatenated with the input.

Hope this clarifies matters.
